services:
  index_bot:
    image: registry.melroy.org/melroy/index-bot/index-bot:latest
    container_name: index_bot
    restart: always
    networks:
      - index_bot_external_network
    volumes:
      - /home/username/folder/to/config.yml:/app/config.yml:ro
      - /home/username/folder/to/tmp:/app/tmp
    ports:
      - "3008:3008"

networks:
  index_bot_external_network:
